# Generated by Django 5.2.3 on 2025-06-28 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ИП", "ИП"),
                            ("Торговая сеть", "Сетевой магазин"),
                            ("Завод", "Завод"),
                        ],
                        max_length=200,
                        verbose_name="Собственник",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("address", models.CharField(max_length=300, verbose_name="адрес")),
                ("is_supplier", models.BooleanField()),
                (
                    "dept",
                    models.FloatField(
                        default=0.0, verbose_name="задолженность перед поставщиком"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trade_net.netunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Звено торговой сети",
                "verbose_name_plural": "Торговая сеть",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("model", models.CharField(max_length=200, verbose_name="Модель")),
                (
                    "release_date",
                    models.DateField(verbose_name="Дата выхода продукта на рынок"),
                ),
                (
                    "manufacture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trade_net.netunit",
                        verbose_name="Завод изготовитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
