# Generated by Django 5.2.3 on 2025-06-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_net", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="netunit",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="trade_net.product",
                verbose_name="Каталог товаров",
            ),
        ),
    ]
