# Generated by Django 5.2.3 on 2025-06-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trade_net", "0002_netunit_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="netunit",
            name="products",
        ),
    ]
