# Generated by Django 5.2.3 on 2025-06-29 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_net", "0003_remove_netunit_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="manufacture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="trade_net.netunit",
                verbose_name="Завод изготовитель",
            ),
        ),
    ]
