# Generated by Django 5.2.3 on 2025-06-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_net", "0004_alter_product_manufacture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="netunit",
            name="is_supplier",
            field=models.BooleanField(default=False),
        ),
    ]
