# Generated by Django 5.2.3 on 2025-06-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trade_net", "0005_alter_netunit_is_supplier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="netunit",
            old_name="type",
            new_name="unit_type",
        ),
    ]
