# Generated by Django 5.2.3 on 2025-06-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_net", "0006_rename_type_netunit_unit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="netunit",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Название"
            ),
        ),
    ]
