# Generated by Django 5.2.3 on 2025-06-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_net", "0007_alter_netunit_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="netunit",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Название"),
        ),
    ]
